-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 16:38:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

use ha_kjc24443;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant` (
  `rest_id` VARCHAR(45) NOT NULL,
  `rest_rating` INT NULL,
  `rest_payroll` DECIMAL(10,2) NULL,
  `rest_name` VARCHAR(45) NULL,
  `rest_city` VARCHAR(45) NULL,
  `rest_state` VARCHAR(45) NULL,
  `rest_traffic` INT NULL,
  PRIMARY KEY (`rest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food` (
  `food_id` VARCHAR(45) NOT NULL,
  `food_gluten_free` ENUM('Yes', 'No') NULL,
  `food_calorie_count` INT NULL,
  `food_type` VARCHAR(45) NULL,
  `food_rating` INT NULL,
  `food_cost` DECIMAL(10,2) NULL,
  `restaurant_rest_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `fk_food_restaurant_idx` (`restaurant_rest_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_restaurant`
    FOREIGN KEY (`restaurant_rest_id`)
    REFERENCES `restaurant` (`rest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO restaurant VALUES
('R001', 5, 50000.00, 'The Spicy Spoon', 'New York', 'NY', 1200),
('R002', 4, 45000.50, 'Ocean Breeze Diner', 'Los Angeles', 'CA', 900),
('R003', 3, 30000.75, 'Mountain View Grill', 'Denver', 'CO', 700),
('R004', 4, 40000.00, 'Golden Dragon', 'San Francisco', 'CA', 850),
('R005', 5, 60000.00, 'Pasta Paradise', 'Chicago', 'IL', 1500),
('R006', 2, 20000.20, 'Budget Bites', 'Austin', 'TX', 500),
('R007', 5, 70000.00, 'Luxury Eats', 'Miami', 'FL', 1800),
('R008', 4, 50000.30, 'Vegan Delight', 'Portland', 'OR', 1000),
('R009', 3, 35000.10, 'City Snacks', 'Seattle', 'WA', 600),
('R010', 5, 75000.00, 'The Gourmet Spot', 'Boston', 'MA', 1600);

INSERT INTO food VALUES
('F001', 'Yes', 250, 'Salad', 5, 12.50, 'R001'),
('F002', 'No', 800, 'Burger', 4, 15.00, 'R001'),
('F003', 'Yes', 100, 'Smoothie', 5, 8.50, 'R002'),
('F004', 'No', 700, 'Pizza', 4, 20.00, 'R002'),
('F005', 'Yes', 150, 'Soup', 3, 10.00, 'R003'),
('F006', 'No', 900, 'Steak', 5, 25.00, 'R004'),
('F007', 'Yes', 200, 'Vegan Wrap', 4, 14.50, 'R005'),
('F008', 'No', 1200, 'Pasta', 5, 18.00, 'R005'),
('F009', 'Yes', 300, 'Grain Bowl', 4, 11.00, 'R006'),
('F010', 'No', 600, 'Fish Tacos', 5, 16.50, 'R007');

select *
	from restaurant;

